version: "3"
services:
    dms-backend:
        image: registry.rangdong2020.ml/dms-backend:latest
        restart: always
        command: ./docker-entrypoint.sh
        volumes:
            - ./consul/:/consul/config
        ports:
            - "5003"
